baseURL = "https://dineshba.github.io/"
languageCode = "en-us"
title = "Dinesh's Blog"
theme = "hyde"
googleAnalytics = "UA-146789724-1"
disqusShortname = "https-dineshba-github-io"

[params]
  themeColor = "theme-base-0d"
  description = "Website to share my learnings"
[Menus]
  main = [
      {Name = "My Talks", URL = "/talks"},
      {Name = "Github", URL = "https://github.com/dineshba/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/dineshba/"},
      {Name = "Stackoverflow", URL = "https://stackoverflow.com/users/5305962/dinesh-balasubramanian"},
      {Name = "Thoughtworks", URL= "https://www.thoughtworks.com/profiles/dinesh-b"}
      ]
