name: 'Deploy'

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate hugo files
      run: |
        wget -q "https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.tar.gz" -O "hugo.tar.gz"
        tar -xzf hugo.tar.gz
        ./hugo
    
    - name: Clone dineshba.github.io
      run: git clone https://github.com/dineshba/dineshba.github.io
      
    - name: Copy files to dineshba.github.io repo
      run: |
        ls -la
        pwd
        ls -la dineshba.github.io/
        cp -rf public/* dineshba.github.io/
    - name: Commit files
      run: |
        cd dineshba.github.io/
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git status
        git add .
        git commit -m "Deploy dineshba/dineshba.github.io"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: dineshba.github.io/
        github_token: ${{ secrets.PUSH_TOKEN }}
        branch: master
        repository: dineshba/dineshba.github.io
